In [2]:
import torch
import numpy as np
import cv2
import matplotlib.pylab as plt

print(f"torch version:{torch.__version__}, cuda version:{torch.version.cuda}, cuda is available:{torch.cuda.is_available()}")

SplitLine = "\n==============================\n"

def PrintTensor(name:str, x:torch.Tensor):
    print(f"{name}:\n", x)
    print(f"{name}的维度数(秩):{x.dim()}; 形状:{x.shape}; 所在设备:{x.device}; 元素个数:{x.numel()}; 元素类型:{x.dtype}, 元素的字节大小:{x.element_size()}", end=SplitLine)

def PrintArray(name:str, x:np.ndarray):
    print(f"{name}:\n", x)
    print(f"{name}的维度数(秩):{x.ndim}; 元素类型：{x.dtype}; 数组的维度形状：{x.shape}; 元素个数：{x.size}; 元素的字节大小：{x.itemsize}", end=SplitLine)

torch version:1.12.1+cu113, cuda version:11.3, cuda is available:True


* Tensor的数组迭代访问与numpy相似

In [13]:
a = torch.randint(0, 20, size=(3, 2, 3))
PrintTensor("a", a)

for i, iv in enumerate(a):
    PrintTensor(f"a[{i},...]", iv)
    for j, jv in enumerate(iv):
        PrintTensor(f"  a[{i},{j},...]", jv)
        for k, kv in enumerate(jv):
            PrintTensor(f"      a[{i},{j},{k}]", kv)

print(SplitLine)
d0, d1, d2 = a.shape
for i in range(d0):
    PrintTensor(f"a[{i},...]", a[i,...])
    for j in range(d1):
        PrintTensor(f"  a[{i},{j},...]", a[i,j,...])
        for k in range(d2):
            PrintTensor(f"      a[{i},{j},{k}]", a[i,j,k])

a:
 tensor([[[12, 18, 12],
         [ 4,  1,  2]],

        [[19,  3, 15],
         [ 7, 12,  1]],

        [[16, 19,  5],
         [19, 18, 12]]])
a的维度数(秩):3; 形状:torch.Size([3, 2, 3]); 所在设备:cpu; 元素个数:18; 元素类型:torch.int64, 元素的字节大小:8
a[0,...]:
 tensor([[12, 18, 12],
        [ 4,  1,  2]])
a[0,...]的维度数(秩):2; 形状:torch.Size([2, 3]); 所在设备:cpu; 元素个数:6; 元素类型:torch.int64, 元素的字节大小:8
  a[0,0,...]:
 tensor([12, 18, 12])
  a[0,0,...]的维度数(秩):1; 形状:torch.Size([3]); 所在设备:cpu; 元素个数:3; 元素类型:torch.int64, 元素的字节大小:8
      a[0,0,0]:
 tensor(12)
      a[0,0,0]的维度数(秩):0; 形状:torch.Size([]); 所在设备:cpu; 元素个数:1; 元素类型:torch.int64, 元素的字节大小:8
      a[0,0,1]:
 tensor(18)
      a[0,0,1]的维度数(秩):0; 形状:torch.Size([]); 所在设备:cpu; 元素个数:1; 元素类型:torch.int64, 元素的字节大小:8
      a[0,0,2]:
 tensor(12)
      a[0,0,2]的维度数(秩):0; 形状:torch.Size([]); 所在设备:cpu; 元素个数:1; 元素类型:torch.int64, 元素的字节大小:8
  a[0,1,...]:
 tensor([4, 1, 2])
  a[0,1,...]的维度数(秩):1; 形状:torch.Size([3]); 所在设备:cpu; 元素个数:3; 元素类型:torch.int64, 元素的字节大小:8
      a[0,1,0]:
 tenso