In [74]:
import torch
from torch import Tensor
import numpy as np

print(f"torch version:{torch.__version__}, cuda version:{torch.version.cuda}, cuda is available:{torch.cuda.is_available()}")

SplitLine = "\n==============================\n"

def PrintTensor(name:str, x:Tensor):
    print(f"{name}:\n", x)
    print(f"{name}的维度数(秩):{x.dim()}; 形状:{x.shape}; 所在设备:{x.device}; 元素个数:{x.numel()}; 元素类型:{x.dtype}, 元素的字节大小:{x.element_size()}", end=SplitLine)

def PrintArray(name:str, x:np.ndarray):
    print(f"{name}:\n", x)
    print(f"{name}的维度数(秩):{x.ndim}; 元素类型：{x.dtype}; 数组的维度形状：{x.shape}; 元素个数：{x.size}; 元素的字节大小：{x.itemsize}", end=SplitLine)

# 与numpy相比，形状都为shape
# 在numpy中，size是指所包含的元素个数；在pytorch中size依然为形状，其包含的元素个数为numel
# 在numpy中，元素的字节大小为itemsize；在pytorch中为element_size

torch version:1.12.1+cu113, cuda version:11.3, cuda is available:True


### Tensor创建  
|函数|功能|
|:---|:---|
|Tensor(*sizes)|基础构造函数|
|tensor(data)|类似于np.array|
|ones(*sizes)|全1|
|zeros(*sizes)|全0|
|eye(*sizes)|对角为1，其余为0|
|arange(s,e,step)|从s到e，步长为step|
|linspace(s,e,steps)|从s到e，均匀分成step份|
|rand/randn(*sizes)|rand是[0,1)均匀分布；randn是服从N(0，1)的正态分布|
|normal(mean,std)|正态分布(均值为mean，标准差是std)|
|randperm(m)|随机排列|

* torch.Tensor与torch.tensor创建

In [45]:
a = Tensor((3, 4))
PrintTensor("a", a)

a1 = Tensor(3, 4)
PrintTensor("a1", a1)

# tensor方法只能使用value形式创建张量
a2 = torch.tensor((3, 4), dtype=torch.int64)
PrintTensor("a2", a2)

# 此方法构建，两种方法默认的数据类型不同，Tensor方法数据默认为float32
na = np.random.randint(0, 50, size=(3, 4))
a3 = torch.Tensor(na)
PrintTensor("a3", a3)
a4 = torch.tensor(na,device="cuda")
PrintTensor("a4", a4)


a:
tensor([3., 4.])
a的维度数(秩):1; 形状:torch.Size([2]); 所在设备:cpu; 元素个数:2; 元素类型:torch.float32, 元素的字节大小:4
a1:
tensor([[2.8026e-45, 0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 1.4013e-45, 0.0000e+00]])
a1的维度数(秩):2; 形状:torch.Size([3, 4]); 所在设备:cpu; 元素个数:12; 元素类型:torch.float32, 元素的字节大小:4
a2:
tensor([3, 4])
a2的维度数(秩):1; 形状:torch.Size([2]); 所在设备:cpu; 元素个数:2; 元素类型:torch.int64, 元素的字节大小:8
a3:
tensor([[45.,  6.,  5., 40.],
        [29., 16.,  3., 46.],
        [11., 29., 30., 15.]])
a3的维度数(秩):2; 形状:torch.Size([3, 4]); 所在设备:cpu; 元素个数:12; 元素类型:torch.float32, 元素的字节大小:4
a4:
tensor([[45,  6,  5, 40],
        [29, 16,  3, 46],
        [11, 29, 30, 15]], device='cuda:0')
a4的维度数(秩):2; 形状:torch.Size([3, 4]); 所在设备:cuda:0; 元素个数:12; 元素类型:torch.int64, 元素的字节大小:8


* 创建特殊张量

In [47]:
a0 = torch.zeros((3, 4))
PrintTensor("a0", a0)

a1 = torch.ones((3, 4), dtype=torch.int64)
PrintTensor("a1", a1)

a3 = torch.eye(3)
PrintTensor("a3", a3)

# torch中只能创建方阵的eye，numpy中可以创建行列不同的eye
b3 = np.eye(3, 4)
PrintArray("b3", b3)

a4 = torch.empty((3, 4))
PrintTensor("a4", a4)

a5 = torch.arange(0, 12)
PrintTensor("a5", a5)
# view只能在数据连续时使用
# 在满足tensor连续性条件时，a.reshape返回的结果与a.view()相同，否则返回的结果与a.contiguous().view()相同
a6 = a5.reshape((3, 4))
PrintTensor("a6", a6)
a7 = a5.view((3, 4))
PrintTensor("a7", a7)

a8 = torch.linspace(0, 12, 6)
PrintTensor("a8", a8)

a0:
tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])
a0的维度数(秩):2; 形状:torch.Size([3, 4]); 所在设备:cpu; 元素个数:12; 元素类型:torch.float32, 元素的字节大小:4
a1:
tensor([[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]])
a1的维度数(秩):2; 形状:torch.Size([3, 4]); 所在设备:cpu; 元素个数:12; 元素类型:torch.int64, 元素的字节大小:8
a3:
tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])
a3的维度数(秩):2; 形状:torch.Size([3, 3]); 所在设备:cpu; 元素个数:9; 元素类型:torch.float32, 元素的字节大小:4
b3:
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]]
维度数(秩):2; 元素类型：float64; 数组的维度形状：(3, 4); 元素个数：12; 元素的字节大小：8
a4:
tensor([[1.9524e-35, 0.0000e+00, 4.4634e-35, 0.0000e+00],
        [7.2708e+31, 5.0778e+31, 3.2608e-12, 1.7728e+28],
        [7.0367e+22, 2.1715e-18, 8.4030e+20, 1.0478e+21]])
a4的维度数(秩):2; 形状:torch.Size([3, 4]); 所在设备:cpu; 元素个数:12; 元素类型:torch.float32, 元素的字节大小:4
a5:
tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])
a5的维度数(秩):1; 形状:torch.Size([12]); 所在设备:cpu; 元素个数:12; 元素类型:torch.int64, 元素的字节大小:8
a6:
tens

* 随机张量创建

In [50]:
a = torch.rand((3, 4))
PrintTensor("a", a)
a1 = torch.randn((3, 4))
PrintTensor("a1", a1)
a2 = torch.randint(0, 50, size=(3, 4))
PrintTensor("a2", a2)

mean = 127.5
std = 20.
a3 = torch.normal(mean, std, size=(3, 4))
PrintTensor("a3", a3)

a4 = torch.randperm(20)
PrintTensor("a4", a4)

a:
tensor([[0.3770, 0.3130, 0.1088, 0.9967],
        [0.4683, 0.8490, 0.7908, 0.1349],
        [0.4946, 0.0377, 0.7500, 0.8541]])
a的维度数(秩):2; 形状:torch.Size([3, 4]); 所在设备:cpu; 元素个数:12; 元素类型:torch.float32, 元素的字节大小:4
a1:
tensor([[ 1.6865,  0.9435, -0.5117, -0.3690],
        [ 1.6485, -0.6723, -0.2845, -1.1416],
        [-0.5012, -1.0045, -0.0452,  2.3697]])
a1的维度数(秩):2; 形状:torch.Size([3, 4]); 所在设备:cpu; 元素个数:12; 元素类型:torch.float32, 元素的字节大小:4
a2:
tensor([[ 2, 30, 14, 43],
        [36, 45, 38,  9],
        [42, 20, 24,  2]])
a2的维度数(秩):2; 形状:torch.Size([3, 4]); 所在设备:cpu; 元素个数:12; 元素类型:torch.int64, 元素的字节大小:8
a3:
tensor([[128.6178, 128.6328, 117.3280, 162.6013],
        [162.6561, 104.6757, 142.3671,  95.0242],
        [154.9756, 160.0784, 118.6222, 102.1500]])
a3的维度数(秩):2; 形状:torch.Size([3, 4]); 所在设备:cpu; 元素个数:12; 元素类型:torch.float32, 元素的字节大小:4
a4:
tensor([ 1,  3, 12, 18,  8, 14, 11, 15,  0,  7,  6, 17,  2,  4,  5, 16,  9, 19,
        10, 13])
a4的维度数(秩):1; 形状:torch.Size([20]); 所在设备:cpu; 元素个数:20

* 从numpy数组/list创建张量

In [62]:
na = np.random.randint(1, 20, size=(3, 4))
PrintArray("na", na)

a = torch.Tensor(na)
PrintTensor("a", a)
a1 = torch.tensor(na)
PrintTensor("a1", a1)
a2 = torch.from_numpy(na)
PrintTensor("a2", a2)
a3 = torch.as_tensor(na)
PrintTensor("a3", a3)
a4 = torch.asarray(na)
PrintTensor("a4", a4)

# numpy ndarray 转list
la = na.tolist()

print("la:\n", la)
b = torch.Tensor(la)
PrintTensor("b", b)
b1 = torch.tensor(la)
PrintTensor("b1", b1)
b2 = torch.as_tensor(la)
PrintTensor("b2", b2)
b3 = torch.asarray(la)
PrintTensor("b3", b3)

# Tensor转ndarray
s = a.numpy()
PrintArray("s", s)

# Tensor转list
l = a.tolist()
print("l:\n", l)

na:
[[11 19 18 16]
 [19  2  2 12]
 [18  8 14 12]]
维度数(秩):2; 元素类型：int64; 数组的维度形状：(3, 4); 元素个数：12; 元素的字节大小：8
a:
tensor([[11., 19., 18., 16.],
        [19.,  2.,  2., 12.],
        [18.,  8., 14., 12.]])
a的维度数(秩):2; 形状:torch.Size([3, 4]); 所在设备:cpu; 元素个数:12; 元素类型:torch.float32, 元素的字节大小:4
a1:
tensor([[11, 19, 18, 16],
        [19,  2,  2, 12],
        [18,  8, 14, 12]])
a1的维度数(秩):2; 形状:torch.Size([3, 4]); 所在设备:cpu; 元素个数:12; 元素类型:torch.int64, 元素的字节大小:8
a2:
tensor([[11, 19, 18, 16],
        [19,  2,  2, 12],
        [18,  8, 14, 12]])
a2的维度数(秩):2; 形状:torch.Size([3, 4]); 所在设备:cpu; 元素个数:12; 元素类型:torch.int64, 元素的字节大小:8
a3:
tensor([[11, 19, 18, 16],
        [19,  2,  2, 12],
        [18,  8, 14, 12]])
a3的维度数(秩):2; 形状:torch.Size([3, 4]); 所在设备:cpu; 元素个数:12; 元素类型:torch.int64, 元素的字节大小:8
a4:
tensor([[11, 19, 18, 16],
        [19,  2,  2, 12],
        [18,  8, 14, 12]])
a4的维度数(秩):2; 形状:torch.Size([3, 4]); 所在设备:cpu; 元素个数:12; 元素类型:torch.int64, 元素的字节大小:8
la:
 [[11, 19, 18, 16], [19, 2, 2, 12], [18, 8, 14,

* 张量的元素标量值访问

In [76]:
PrintTensor("a", a)

a_mean = a.mean()
PrintTensor("a_mean", a_mean)

# item方法只有当Tensor中含有一个元素时可用
a_val = a_mean.item()
print("a_val type: ", type(a_val))
print("a_val:\n", a_val)

a_11 = a[1][1]
PrintTensor("a_11 Tensor", a_11)
print("a_11:\n", a_11.item())

# 访问多个标量值需要将其转成numpy或者list
a_mean_0 = a.mean(dim=0)
PrintTensor("a_mean_0", a_mean_0)
PrintArray("a_mean_0 ndarray", a_mean_0.numpy())
a_mean_1 = a.mean(dim=1)
PrintTensor("a_mean_1", a_mean_1)
print("a_mean_1 list:\n", a_mean_1.tolist())

a:
 tensor([[11., 19., 18., 16.],
        [19.,  2.,  2., 12.],
        [18.,  8., 14., 12.]])
a的维度数(秩):2; 形状:torch.Size([3, 4]); 所在设备:cpu; 元素个数:12; 元素类型:torch.float32, 元素的字节大小:4
a_mean:
 tensor(12.5833)
a_mean的维度数(秩):0; 形状:torch.Size([]); 所在设备:cpu; 元素个数:1; 元素类型:torch.float32, 元素的字节大小:4
a_val type:  <class 'float'>
a_val:
 12.583333015441895
a_11 Tensor:
 tensor(2.)
a_11 Tensor的维度数(秩):0; 形状:torch.Size([]); 所在设备:cpu; 元素个数:1; 元素类型:torch.float32, 元素的字节大小:4
a_11:
 2.0
a_mean_0:
 tensor([16.0000,  9.6667, 11.3333, 13.3333])
a_mean_0的维度数(秩):1; 形状:torch.Size([4]); 所在设备:cpu; 元素个数:4; 元素类型:torch.float32, 元素的字节大小:4
a_mean_0 ndarray:
 [16.        9.666667 11.333333 13.333333]
a_mean_0 ndarray的维度数(秩):1; 元素类型：float32; 数组的维度形状：(4,); 元素个数：4; 元素的字节大小：4
a_mean_1:
 tensor([16.0000,  8.7500, 13.0000])
a_mean_1的维度数(秩):1; 形状:torch.Size([3]); 所在设备:cpu; 元素个数:3; 元素类型:torch.float32, 元素的字节大小:4
a_mean_1 list:
 [16.0, 8.75, 13.0]
