In [2]:
import torch
# import numpy as np
# import cv2
# import matplotlib.pylab as plt

print(f"torch version:{torch.__version__}, cuda version:{torch.version.cuda}, cuda is available:{torch.cuda.is_available()}")

SplitLine = "\n==============================\n"

def PrintTensor(name:str, x:torch.Tensor):
    print(f"{name}:\n", x)
    print(f"{name}的维度数(秩):{x.dim()}; 形状:{x.shape}; 所在设备:{x.device}; 元素个数:{x.numel()}; 元素类型:{x.dtype}, 元素的字节大小:{x.element_size()}", end=SplitLine)

torch version:1.12.1+cu113, cuda version:11.3, cuda is available:True


* 改变张量形状

|函数|作用|
|:---|:---|
|flatten|通过将输入重塑为一维张量来展平输入|
|ravel|返回一个连续的平坦张量|
|reshape|返回一个张量，该张量具有与输入相同的数据和元素数，但具有指定的形状|
|view|返回一个新的张量，该张量的数据与自张量相同，但形状不同|
|squeeze|返回删除了大小为1的输入的所有维度的张量|
|unsqueeze|返回一个新的张量，在指定位置插入大小为1的维度|
|unbind|移除指定维度，返回以该维度上的多个张量组成的元组|

In [27]:
a = torch.randint(0, 20, size=(3, 2, 3))
PrintTensor("a", a)

b = a.flatten()
PrintTensor("b", b)
bv = a.ravel()
PrintTensor("bv", bv)

a1 = a.reshape((3, 3, 2))
PrintTensor("a1", a1)

a2 = a.view((3, 3, 2))
PrintTensor("a2", a2)

# permute与numpy中transpose用法相似
a_ = a.permute((1, 0, 2))
PrintTensor("a_", a_)
b_ = a_.flatten()
PrintTensor("b_", b_)
b_v = a_.ravel()
PrintTensor("b_v", b_v)

a_1 = a_.reshape((3, 3, 2))
PrintTensor("a_1", a_1)
# 由于经过维度变换，此时数据排列并不连续，因此不能使用view操作改变形状，只能使用reshape
# a_2 = a_.view((3, 3, 2))  #不能直接使用
a_2 = a_.contiguous()  # 是内存数据连续
a_2 = a_2.reshape((3, 3, 2))
PrintTensor("a_2", a_2)

ae1 = torch.unsqueeze(a, 0)
PrintTensor("ae1", ae1)
ae11 = ae1.unsqueeze(2)
PrintTensor("ae11", ae11)

# 未指定dim则将所有为1的dim进行压缩删除
ae11s = ae11.squeeze()
PrintTensor("ae11s", ae11s)

ae1s = torch.squeeze(ae1, 0)
PrintTensor("ae1s", ae1s)

anb = torch.unbind(a, 1)
print("anb:\n", anb)

a:
 tensor([[[14, 13, 13],
         [ 3,  1,  6]],

        [[ 0,  0,  0],
         [15,  4, 12]],

        [[15,  5,  5],
         [ 9, 14,  2]]])
a的维度数(秩):3; 形状:torch.Size([3, 2, 3]); 所在设备:cpu; 元素个数:18; 元素类型:torch.int64, 元素的字节大小:8
b:
 tensor([14, 13, 13,  3,  1,  6,  0,  0,  0, 15,  4, 12, 15,  5,  5,  9, 14,  2])
b的维度数(秩):1; 形状:torch.Size([18]); 所在设备:cpu; 元素个数:18; 元素类型:torch.int64, 元素的字节大小:8
bv:
 tensor([14, 13, 13,  3,  1,  6,  0,  0,  0, 15,  4, 12, 15,  5,  5,  9, 14,  2])
bv的维度数(秩):1; 形状:torch.Size([18]); 所在设备:cpu; 元素个数:18; 元素类型:torch.int64, 元素的字节大小:8
a1:
 tensor([[[14, 13],
         [13,  3],
         [ 1,  6]],

        [[ 0,  0],
         [ 0, 15],
         [ 4, 12]],

        [[15,  5],
         [ 5,  9],
         [14,  2]]])
a1的维度数(秩):3; 形状:torch.Size([3, 3, 2]); 所在设备:cpu; 元素个数:18; 元素类型:torch.int64, 元素的字节大小:8
a2:
 tensor([[[14, 13],
         [13,  3],
         [ 1,  6]],

        [[ 0,  0],
         [ 0, 15],
         [ 4, 12]],

        [[15,  5],
         [ 5,  9],
      

* 维度变换  

|函数|作用|
|:---|:---|
|transpose|返回一个张量，该张量是输入的转置版本|
|permute|返回原始张量输入的视图，并对其维度进行排列|
|t|期望输入为<=2D张量，并转置维度0和1|
|T属性|将源维度倒序翻转|
|movedim/moveaxis|将源中位置处的输入维度移动到目标中的位置|
|swapdims/swapaxes|Alias for torch.transpose()|

In [19]:
a = torch.randint(0, 20, size=(3, 2, 4))
PrintTensor("a", a)

a_t = a.transpose(1, 2)
PrintTensor("a_t", a_t)

a_p = a.permute((0, 2, 1))
PrintTensor("a_p", a_p)

a_t1 = a.T
PrintTensor("a_t1", a_t1)

a2d = a.select(0, 0)
PrintTensor("a2d", a2d)
a_t2 = a2d.t()  # 输入维度最多为2d
PrintTensor("a_t2", a_t2)

a_m1 = a.movedim(1, 0)
PrintTensor("a_m1", a_m1)
a_m2 = a.moveaxis(2, 0)
PrintTensor("a_m2", a_m2)

a:
 tensor([[[ 7, 16,  3, 11],
         [14, 11, 11, 17]],

        [[ 9,  3,  8, 13],
         [17,  0, 15,  3]],

        [[ 9,  5, 19, 11],
         [13, 14, 10, 12]]])
a的维度数(秩):3; 形状:torch.Size([3, 2, 4]); 所在设备:cpu; 元素个数:24; 元素类型:torch.int64, 元素的字节大小:8
a_t:
 tensor([[[ 7, 14],
         [16, 11],
         [ 3, 11],
         [11, 17]],

        [[ 9, 17],
         [ 3,  0],
         [ 8, 15],
         [13,  3]],

        [[ 9, 13],
         [ 5, 14],
         [19, 10],
         [11, 12]]])
a_t的维度数(秩):3; 形状:torch.Size([3, 4, 2]); 所在设备:cpu; 元素个数:24; 元素类型:torch.int64, 元素的字节大小:8
a_p:
 tensor([[[ 7, 14],
         [16, 11],
         [ 3, 11],
         [11, 17]],

        [[ 9, 17],
         [ 3,  0],
         [ 8, 15],
         [13,  3]],

        [[ 9, 13],
         [ 5, 14],
         [19, 10],
         [11, 12]]])
a_p的维度数(秩):3; 形状:torch.Size([3, 4, 2]); 所在设备:cpu; 元素个数:24; 元素类型:torch.int64, 元素的字节大小:8
a_t1:
 tensor([[[ 7,  9,  9],
         [14, 17, 13]],

        [[16,  3,  5],
         [1

* 张量扩充      

|函数|作用|
|:---|:---|
|tile|通过重复输入的元素来构造张量|
|expand|返回自张量的新视图，其中单维度扩展到更大的大小|
|resize_|将自张量的大小调整为指定的大小|

In [58]:
a = torch.randint(0, 20, size=(2, 1, 4))
PrintTensor("a", a)

# 新张量形状为源形状与设置size相应维度相乘
a1 = a.tile((1, 2, 3))
PrintTensor("a1", a1)

# 只能扩充维度为1的
a2 = a.expand((-1, 6, -1))
PrintTensor("a2", a2)

# 该操作会修改源张量内容，且resize方法并不能这样使用
a3 = a.resize_(2, 2, 3)
PrintTensor("a3", a3)
PrintTensor("a", a)

a:
 tensor([[[ 0,  0,  0,  6]],

        [[12, 17, 10, 17]]])
a的维度数(秩):3; 形状:torch.Size([2, 1, 4]); 所在设备:cpu; 元素个数:8; 元素类型:torch.int64, 元素的字节大小:8
a1:
 tensor([[[ 0,  0,  0,  6,  0,  0,  0,  6,  0,  0,  0,  6],
         [ 0,  0,  0,  6,  0,  0,  0,  6,  0,  0,  0,  6]],

        [[12, 17, 10, 17, 12, 17, 10, 17, 12, 17, 10, 17],
         [12, 17, 10, 17, 12, 17, 10, 17, 12, 17, 10, 17]]])
a1的维度数(秩):3; 形状:torch.Size([2, 2, 12]); 所在设备:cpu; 元素个数:48; 元素类型:torch.int64, 元素的字节大小:8
a2:
 tensor([[[ 0,  0,  0,  6],
         [ 0,  0,  0,  6],
         [ 0,  0,  0,  6],
         [ 0,  0,  0,  6],
         [ 0,  0,  0,  6],
         [ 0,  0,  0,  6]],

        [[12, 17, 10, 17],
         [12, 17, 10, 17],
         [12, 17, 10, 17],
         [12, 17, 10, 17],
         [12, 17, 10, 17],
         [12, 17, 10, 17]]])
a2的维度数(秩):3; 形状:torch.Size([2, 6, 4]); 所在设备:cpu; 元素个数:48; 元素类型:torch.int64, 元素的字节大小:8
a3:
 tensor([[[ 0,  0,  0],
         [ 6, 12, 17]],

        [[10, 17,  0],
         [ 0, 26,  1]]])
a3

* 张量的连接与拆分      

|函数|作用|
|:---|:---|
|cat|将给定维度中的seq张量的给定序列连接起来|
|concat|Alias of torch.cat()|
|chunk|将张量拆分为指定数量的块|
|split|将张量拆分为块|
|dsplit|根据indices _or_sections，将输入（一个具有三维或三维以上维度的张量）深度分解为多个张量|
|hsplit|根据indices_or_sections，将输入（一个或多个维度的张量）水平拆分为多个张量|
|vsplit|根据indices_or_sections将输入（一个具有二维或多维的张量）垂直拆分为多个张量|
|tensor_split|根据indices_or_sections指定的索引或节数，沿维度dim将张量拆分为多个子张量，所有子张量都是输入的视图|
|stack|沿着一个新的维度连接一系列张量|
|dstack|按深度顺序堆叠张量（沿第三轴）|
|hstack|按顺序水平堆叠张量（按列）|
|vstack|垂直（按行）按顺序堆叠张量|
|column_stack|通过在张量中水平堆叠张量来创建新的张量,Alias of torch.hstack()|
|row_stack|Alias of torch.vstack()|

In [76]:
a = torch.randint(0, 20, size=(2, 3, 4))
b = torch.randint(20, 50, size=(4, 3, 4))
PrintTensor("a", a)
PrintTensor("b", b)

ab = torch.cat((a, b), dim=0)
PrintTensor("ab", ab)
# concat指定维度连接时，其他维度大小应保持相同
b = torch.randint(20, 50, size=(2, 2, 4))
PrintTensor("b", b)
ab1 = torch.concat((a, b), dim=1)
PrintTensor("ab1", ab1)

chk_lst = torch.chunk(ab, 2, dim=0)
print(f"chk_lst: {len(chk_lst)}\n", chk_lst, end=SplitLine)

sp_lst = torch.split(ab, [2, 4], dim=0)
print(f"sp_lst: {len(sp_lst)}\n", sp_lst, end=SplitLine)

# 索引相当于(0:1),(1:3),(3:)
spd_lst = torch.dsplit(ab, (1, 3))
# torch.split(ab, [1, 2, 1], dim=ab.shape[-1])  # 同上
# torch.tensor_split(ab, [1, 3], dim=ab.shape[-1])

print(f"spd_lst: {len(spd_lst)}\n", spd_lst, end=SplitLine)
sph_lst = torch.hsplit(ab, (2,))
# torch.split(ab, [2, 1], dim=ab.shape[-2])  # 同上
# torch.tensor_split(ab, (2,), dim=ab.shape[-2])
print(f"sph_lst: {len(sph_lst)}\n", sph_lst, end=SplitLine)

spv_lst = torch.vsplit(ab, 2)
# torch.split(ab, 2, dim=ab.shape[-3])  # 同上
# torch.tensor_split(ab, 2, dim=ab.shape[-3])
print(f"spv_lst: {len(spv_lst)}\n", spv_lst, end=SplitLine)

# 在split中，第二参数为平均分块数量或者指定维度的分块大小列表
# 在dsplit，hsplit， vsplit中，第二个参数为平均分块数量或者为指定维度的分块截止索引列表
# 在tensor_split，第二个参数与dsplit，hsplit， vsplit中使用方法一样

PrintTensor("a", a)
b = torch.randint(20, 50, size=(2, 3, 4))
PrintTensor("b", b)
abs0 = torch.stack((a, b), dim=0)
PrintTensor("abs0", abs0)
abs1 = torch.stack((a, b), dim=1)
PrintTensor("abs1", abs1)
abs2 = torch.stack((a, b, a), dim=2)
PrintTensor("abs2", abs2)
# cat 操作将多个张量在指定维度上进行连接，源张量的维度数不会变化
# stack 操作将多个张量在指定维度上进行堆叠，新的张量会在指定维度前增加一个维度，该维度的值为堆叠源张量的数量

abds = torch.dstack((a, b))
PrintTensor("abds", abds)
abhs = torch.hstack((a, b))
PrintTensor("abhs", abhs)
abvs = torch.vstack((a, b))
PrintTensor("abvs", abvs)
abhs1 = torch.column_stack((a, b))
print("abhs eq abhs1: ", abhs.equal(abhs1), end=SplitLine)
abvs1 = torch.row_stack((a, b))
print("abvs eq abvs1: ", abvs.equal(abvs1), end=SplitLine)
# dstack,hstack,vstack,column_stack,row_stack 为cat方法的dim指定，而非stack方法

a:
 tensor([[[ 3,  7, 12,  2],
         [18, 11, 16,  8],
         [15, 13, 11,  0]],

        [[ 6,  1,  6,  4],
         [13, 10,  7,  1],
         [ 8,  4,  9,  1]]])
a的维度数(秩):3; 形状:torch.Size([2, 3, 4]); 所在设备:cpu; 元素个数:24; 元素类型:torch.int64, 元素的字节大小:8
b:
 tensor([[[38, 37, 24, 21],
         [45, 35, 29, 35],
         [39, 30, 41, 26]],

        [[32, 22, 46, 24],
         [28, 28, 31, 21],
         [21, 35, 32, 26]],

        [[27, 31, 32, 35],
         [37, 38, 20, 34],
         [39, 31, 26, 41]],

        [[27, 43, 38, 44],
         [25, 29, 21, 36],
         [20, 39, 47, 41]]])
b的维度数(秩):3; 形状:torch.Size([4, 3, 4]); 所在设备:cpu; 元素个数:48; 元素类型:torch.int64, 元素的字节大小:8
ab:
 tensor([[[ 3,  7, 12,  2],
         [18, 11, 16,  8],
         [15, 13, 11,  0]],

        [[ 6,  1,  6,  4],
         [13, 10,  7,  1],
         [ 8,  4,  9,  1]],

        [[38, 37, 24, 21],
         [45, 35, 29, 35],
         [39, 30, 41, 26]],

        [[32, 22, 46, 24],
         [28, 28, 31, 21],
         [21, 35

* 张量元素的添加与删除      
*在pytorch中，并没有直接对Tensor中的元素进行添加，删除的方法！* 可利用切片与拼接结合或者转换为numpy然后进行操作

* 元素挑选  

|函数|作用|
|:---|:---|
|argwhere|返回一个张量，该张量包含输入的所有非零元素的索引|
|nonzero|返回一个 2D 张量/元组，其中每一行都是一个非零值的索引|
|where|根据条件，返回一个从 x 或 y 中选择元素的张量|
|gather|沿 dim 指定的轴收集值|
|take|返回一个新的张量，其中包含给定索引处的输入元素|
|narrow|返回一个新的张量，它是输入张量的缩小版|
|select|在给定的索引处沿所选维度切分输入张量|
|index_select|返回一个新的张量，该张量使用 LongTensor 索引中的条目沿维度 dim 对输入张量进行索引|
|masked_select|返回一个新的一维张量，该张量根据布尔掩码（即 BoolTensor）对输入张量进行索引|
|select_scatter|将 src 张量的值嵌入给定索引处的输入中|
|diagonal_scatter|根据 dim1 和 dim2 将 src 张量的值沿输入的对角线元素嵌入输入|
|slice_scatter|将 src 张量的值嵌入给定维度的输入中 (难用)|      

"scatter"方法相当于将源张量的值根据指定维度和索引赋值给输入张量，比较难用

In [147]:
a = torch.randint(0, 10, size=(3, 4))
PrintTensor("a", a)

bnz = torch.argwhere(a)
PrintTensor("bnz", bnz)

bnz1 = torch.nonzero(a)
PrintTensor('bnz1', bnz1)

PrintTensor("a", a)
b = torch.randint(0, 20, size=(3, 4))
PrintTensor("b", b)
# 根据条件判断为真，则去a中元素，为假则取0
bw = torch.where(a > b, a, 0)
PrintTensor("bw", bw)

PrintTensor("a", a)
index = torch.tensor([[2, 1, 0, 1, 2], [0, 1, 2, 1, 0]])
PrintTensor("index", index)
# index的维度数需与输入张量的维度数一样
# 输出的张量形状与index的形状一致
bg = torch.gather(a, 1, index)
PrintTensor("bg", bg)

index = torch.tensor([[2, 1, 0, 1], [0, 1, 2, 1]])
PrintTensor("index", index)
bg1 = torch.gather(a, 0, index)
PrintTensor("bg1", bg1)

PrintTensor("a", a)
indices = torch.tensor([[10, 8, 5], [3, 7, 0]])
# 返回一个新的张量，其中的元素是输入元素在给定的索引处，将输入张量视为视为一维张量。结果tensor的形状与索引相同。
btk = torch.take(a, indices)
PrintTensor("btk", btk)

PrintTensor("a", a)
bnar = torch.narrow(a, 1, 1, 2)
PrintTensor("bnar", bnar)

PrintTensor("a", a)
bslct = torch.select(a, 0, 1)
PrintTensor("bslct", bslct)

indices = torch.tensor([0, 2])
# select方法增强版
bislct = torch.index_select(a, 0, indices)
PrintTensor("bislct", bislct)

PrintTensor("a", a)
mask = a.ge(5)
PrintTensor("mask", mask)
ams = torch.masked_select(a, mask)
PrintTensor("ams", ams)

a = torch.zeros(2, 3)
PrintTensor("a", a)
b = torch.ones(3)
PrintTensor("b", b)
ass = a.select_scatter(b, 0, 0)
PrintTensor("ass", ass)
b1 = torch.ones(2)
PrintTensor("b1", b1)
ass1 = torch.select_scatter(a, b1, 1, 0)
PrintTensor("ass1", ass1)


a = torch.randint(1, 20, size=(2, 3))
b = torch.zeros((2, 3, 4))
PrintTensor("a", a)
PrintTensor("b", b)
mds = torch.diagonal_scatter(b, a, dim1=2, dim2=1)
PrintTensor("mds", mds)
a1 = torch.randint(1, 20, size=(4, 2))
PrintTensor("a1", a1)
mds1 = b.diagonal_scatter(a1, dim1=1, dim2=0)
PrintTensor("mds1", mds1)

a = torch.zeros(8, 8)
b = torch.ones(5, 8)
PrintTensor("a", a)
PrintTensor("b", b)
mslcs = a.slice_scatter(b, start=3)
PrintTensor("mslcs", mslcs)
b = torch.ones(8, 3)
mslcs1 = torch.slice_scatter(a, b, dim=1, start=1, end=6, step=2)
PrintTensor("mslcs1", mslcs1)

a:
 tensor([[3, 2, 0, 5],
        [1, 8, 2, 3],
        [9, 9, 5, 0]])
a的维度数(秩):2; 形状:torch.Size([3, 4]); 所在设备:cpu; 元素个数:12; 元素类型:torch.int64, 元素的字节大小:8
bnz:
 tensor([[0, 0],
        [0, 1],
        [0, 3],
        [1, 0],
        [1, 1],
        [1, 2],
        [1, 3],
        [2, 0],
        [2, 1],
        [2, 2]])
bnz的维度数(秩):2; 形状:torch.Size([10, 2]); 所在设备:cpu; 元素个数:20; 元素类型:torch.int64, 元素的字节大小:8
bnz1:
 tensor([[0, 0],
        [0, 1],
        [0, 3],
        [1, 0],
        [1, 1],
        [1, 2],
        [1, 3],
        [2, 0],
        [2, 1],
        [2, 2]])
bnz1的维度数(秩):2; 形状:torch.Size([10, 2]); 所在设备:cpu; 元素个数:20; 元素类型:torch.int64, 元素的字节大小:8
a:
 tensor([[3, 2, 0, 5],
        [1, 8, 2, 3],
        [9, 9, 5, 0]])
a的维度数(秩):2; 形状:torch.Size([3, 4]); 所在设备:cpu; 元素个数:12; 元素类型:torch.int64, 元素的字节大小:8
b:
 tensor([[15,  3, 13, 10],
        [ 6, 17, 16,  0],
        [16,  4, 15, 10]])
b的维度数(秩):2; 形状:torch.Size([3, 4]); 所在设备:cpu; 元素个数:12; 元素类型:torch.int64, 元素的字节大小:8
bw:
 tensor([[0, 0, 0, 

* 其他操作  

|函数|作用|
|:---|:---|
|index_add|将阿尔法乘源的元素累加到自张量中，按索引中给出的顺序加到索引中|
|index_copy|按照索引中给出的顺序选择索引，将张量元素复制到输入张量中|
|index_reduce|使用 reduce 参数给出的还原方法，按 index 中给出的顺序将源元素累加到输入张量中|
|index_fill|按照 index 中给出的顺序选择索引，用数值填充自张量的元素|
|clamp|将输入中的所有元素压缩到 [ 最小值，最大值 ] 范围内|

In [157]:
a = torch.zeros(3, 4, dtype=torch.int64)
PrintTensor("a", a)

b = torch.randint(1, 20, size=(2, 4))
PrintTensor("b", b)

index = torch.tensor([2, 1])
madd = torch.index_add(a, 0, index, b, alpha=1)
PrintTensor("m", madd)

b1 = torch.randint(1, 20, size=(3, 2))
PrintTensor("b1", b1)
madd1 = a.index_add(1, index, b1, alpha=2)
PrintTensor("m1", madd1)

PrintTensor("a", a)
# value 只能是0-dim张量
mfill = torch.index_fill(a, 0, index, 50)
PrintTensor("mfill", mfill)

PrintTensor("a", a)
PrintTensor("b", b)
PrintTensor("index", index)
# 与index_add alpha为1时相同
mcopy = torch.index_copy(a, 0, index, b)
PrintTensor("mcopy", mcopy)
PrintTensor("b1", b1)
mcopy1 = a.index_copy(1, index, b1)
PrintTensor("mcopy1", mcopy1)

a = torch.empty(5, 3).fill_(2)
s = torch.arange(0, 12, dtype=torch.float).view(4, 3)
index = torch.tensor([0, 4, 2, 0])
PrintTensor("a", a)
PrintTensor("s", s)
PrintTensor("index", index)
# reduce 模式可选 "prod","mean", "amax", "amin"
mreduce = torch.index_reduce(a, 0, index, s, "prod")
PrintTensor("mreduce", mreduce)

a = torch.randint(0, 100, size=(3, 3))
mclamp = torch.clamp(a, 20, 80)
PrintTensor("a", a)
PrintTensor("mclamp", mclamp)

a:
 tensor([[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]])
a的维度数(秩):2; 形状:torch.Size([3, 4]); 所在设备:cpu; 元素个数:12; 元素类型:torch.int64, 元素的字节大小:8
b:
 tensor([[ 3, 14,  6, 17],
        [15,  5, 17, 17]])
b的维度数(秩):2; 形状:torch.Size([2, 4]); 所在设备:cpu; 元素个数:8; 元素类型:torch.int64, 元素的字节大小:8
m:
 tensor([[ 0,  0,  0,  0],
        [15,  5, 17, 17],
        [ 3, 14,  6, 17]])
m的维度数(秩):2; 形状:torch.Size([3, 4]); 所在设备:cpu; 元素个数:12; 元素类型:torch.int64, 元素的字节大小:8
b1:
 tensor([[10, 16],
        [ 2, 14],
        [17, 17]])
b1的维度数(秩):2; 形状:torch.Size([3, 2]); 所在设备:cpu; 元素个数:6; 元素类型:torch.int64, 元素的字节大小:8
m1:
 tensor([[ 0, 32, 20,  0],
        [ 0, 28,  4,  0],
        [ 0, 34, 34,  0]])
m1的维度数(秩):2; 形状:torch.Size([3, 4]); 所在设备:cpu; 元素个数:12; 元素类型:torch.int64, 元素的字节大小:8
a:
 tensor([[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]])
a的维度数(秩):2; 形状:torch.Size([3, 4]); 所在设备:cpu; 元素个数:12; 元素类型:torch.int64, 元素的字节大小:8
mfill:
 tensor([[ 0,  0,  0,  0],
        [50, 50, 50, 50],
        [50, 50, 50, 5