In [29]:
import torch
import numpy as np
# import cv2
# import matplotlib.pylab as plt

print(f"torch version:{torch.__version__}, cuda version:{torch.version.cuda}, cuda is available:{torch.cuda.is_available()}")

SplitLine = "\n==============================\n"

def PrintTensor(name:str, x:torch.Tensor):
    print(f"{name}:\n", x)
    print(f"{name}的维度数(秩):{x.dim()}; 形状:{x.shape}; 所在设备:{x.device}; 元素个数:{x.numel()}; 元素类型:{x.dtype}, 元素的字节大小:{x.element_size()}", end=SplitLine)

torch version:1.12.1+cu113, cuda version:11.3, cuda is available:True


* 张量元素基础计算  

|函数|作用|
|:---|:---|
|abs|计算输入中每个元素的绝对值|
|add|将按alpha缩放的其他加到输入|
|sub|使用输入减去将按alpha缩放的其他|
|mul|两个张量进行对应元素相乘|
|div|两个张量进行元素相除|
|pow|求n次方的值|
|sign|用来取某个数的符号，符号函数如果在0点不定义|
|reciprocal|每个元素的倒数|
|sqrt|对每个元素取平方根|
|rsqrt|对每个元素取平方根后再取倒数|
|neg|元素取负|
|lerp|对两个张量以start, end做线性插值，将结果返回到输出张量out = start + weight*(end - start)|
|addcdiv|用tensor2对tensor1逐元素相除，然后乘以标量值value并加到tensor上|
|addcmul|用tensor2对tensor1逐元素相乘，并对结果乘以标量值value然后加到tensor，张量形状不需要匹配，但元素数量必须一致|
|cumprod|返回输入沿指定维度的累积积|
|cumsum|返回输入沿指定维度的累积和|
|floor|向下取整|
|ceil|向上取整|
|round|四舍五入|
|trunc|裁剪，只保留整数部分|
|frac|只保留小数部分|
|%|取余|

In [34]:
a = torch.empty(2, 3, 4, dtype=torch.int64).fill_(-2)
PrintTensor("a", a)
b = torch.empty_like(a, dtype=torch.int64).fill_(9)
PrintTensor("b", b)

# 加
madd = a + b
PrintTensor("madd", madd)
madd1 = a.add(b)
PrintTensor("madd1", madd1)
madd2 = torch.add(a, b, alpha=2)
PrintTensor("madd2", madd2)

# 减
msub = b - a
PrintTensor("msub", msub)
msub1 = b.sub(a)
PrintTensor("msub1", msub1)
msub2 = torch.sub(b, a, alpha=2)
PrintTensor("msub2", msub2)

# 乘
mmul = a * b
PrintTensor("mmul", mmul)
mmul1 = a.mul(b)
PrintTensor("mmul1", mmul1)
mmul2 = torch.mul(a, b)
PrintTensor("mmul2", mmul2)

# 除
b.to(torch.float)
mdiv = b / 2.
PrintTensor("mdiv", mdiv)
mdiv1 = b.div(3., rounding_mode="trunc")
PrintTensor("mdiv1", mdiv1)
mdiv2 = torch.div(b, a.to(torch.float), rounding_mode="floor")
PrintTensor("mdiv2", mdiv2)

# 绝对值
mabs = a.abs()
PrintTensor("mabs", mabs)
mabs1 = torch.abs(a)
PrintTensor("mabs1", mabs1)

a:
 tensor([[[-2, -2, -2, -2],
         [-2, -2, -2, -2],
         [-2, -2, -2, -2]],

        [[-2, -2, -2, -2],
         [-2, -2, -2, -2],
         [-2, -2, -2, -2]]])
a的维度数(秩):3; 形状:torch.Size([2, 3, 4]); 所在设备:cpu; 元素个数:24; 元素类型:torch.int64, 元素的字节大小:8
b:
 tensor([[[9, 9, 9, 9],
         [9, 9, 9, 9],
         [9, 9, 9, 9]],

        [[9, 9, 9, 9],
         [9, 9, 9, 9],
         [9, 9, 9, 9]]])
b的维度数(秩):3; 形状:torch.Size([2, 3, 4]); 所在设备:cpu; 元素个数:24; 元素类型:torch.int64, 元素的字节大小:8
madd:
 tensor([[[7, 7, 7, 7],
         [7, 7, 7, 7],
         [7, 7, 7, 7]],

        [[7, 7, 7, 7],
         [7, 7, 7, 7],
         [7, 7, 7, 7]]])
madd的维度数(秩):3; 形状:torch.Size([2, 3, 4]); 所在设备:cpu; 元素个数:24; 元素类型:torch.int64, 元素的字节大小:8
madd1:
 tensor([[[7, 7, 7, 7],
         [7, 7, 7, 7],
         [7, 7, 7, 7]],

        [[7, 7, 7, 7],
         [7, 7, 7, 7],
         [7, 7, 7, 7]]])
madd1的维度数(秩):3; 形状:torch.Size([2, 3, 4]); 所在设备:cpu; 元素个数:24; 元素类型:torch.int64, 元素的字节大小:8
madd2:
 tensor([[[16, 16, 16, 16],
   

* 张量元素位运算  

|函数|作用|
|:---|:---|
|bitwise_not|计算给定输入张量按位取“反”|
|bitwise_and|计算输入和其他的按位“与”|
|bitwise_or|计算输入和其他的按位“或”|
|bitwise_xor|计算输入和其他的按位异或|
|bitwise_left_shift|计算输入的其他位数的左移算术值|
|bitwise_right_shift|按其他位计算输入的算术右移|

In [44]:
# 取反
a = torch.empty(2, 3, 4, dtype=torch.int8).fill_(3)
PrintTensor("a", a)
print("a bin:\n", np.binary_repr(a[0, 0, 0], width=8), end=SplitLine)
mnot = torch.bitwise_not(a)
PrintTensor("mnot", mnot)
print("mnot bin:\n", np.binary_repr(mnot[0, 0, 0], width=8), end=SplitLine)

# 求与
b = torch.empty(2, 3, 4, dtype=torch.uint8).fill_(5)
PrintTensor("b", b)
print("b bin:\n", np.binary_repr(b[0, 0, 0], width=8), end=SplitLine)
mand = a.bitwise_and(b)
PrintTensor("mand", mand)
print("mand bin:\n", np.binary_repr(mand[0, 0, 0], width=8), end=SplitLine)

# 求或
mor = torch.bitwise_or(a, b)
PrintTensor("mor", mor)
print("mor bin:\n", np.binary_repr(mor[0, 0, 0], width=8), end=SplitLine)

# 求异或
mxor = a.bitwise_xor(b)
PrintTensor("mxor", mxor)
print("mxor bin:\n", np.binary_repr(mxor[0, 0, 0], width=8), end=SplitLine)

# 左移
print("a bin:\n", np.binary_repr(a[0, 0, 0], width=8), end=SplitLine)
b = torch.empty(2, 3, 4, dtype=torch.int8).fill_(2)
mls = torch.bitwise_left_shift(a, b)
PrintTensor("mls", mls)
print("mls bin:\n", np.binary_repr(mls[0, 0, 0], width=8), end=SplitLine)

# 右移
a = torch.empty(2, 3, 4, dtype=torch.int8).fill_(12)
PrintTensor("a", a)
print("a bin:\n", np.binary_repr(a[0, 0, 0], width=8), end=SplitLine)
mrs = a.bitwise_right_shift(b)
PrintTensor("mrs", mrs)
print("mrs bin:\n", np.binary_repr(mrs[0, 0, 0], width=8), end=SplitLine)

a:
 tensor([[[3, 3, 3, 3],
         [3, 3, 3, 3],
         [3, 3, 3, 3]],

        [[3, 3, 3, 3],
         [3, 3, 3, 3],
         [3, 3, 3, 3]]], dtype=torch.int8)
a的维度数(秩):3; 形状:torch.Size([2, 3, 4]); 所在设备:cpu; 元素个数:24; 元素类型:torch.int8, 元素的字节大小:1
a bin:
 00000011
mnot:
 tensor([[[-4, -4, -4, -4],
         [-4, -4, -4, -4],
         [-4, -4, -4, -4]],

        [[-4, -4, -4, -4],
         [-4, -4, -4, -4],
         [-4, -4, -4, -4]]], dtype=torch.int8)
mnot的维度数(秩):3; 形状:torch.Size([2, 3, 4]); 所在设备:cpu; 元素个数:24; 元素类型:torch.int8, 元素的字节大小:1
mnot bin:
 11111100
b:
 tensor([[[5, 5, 5, 5],
         [5, 5, 5, 5],
         [5, 5, 5, 5]],

        [[5, 5, 5, 5],
         [5, 5, 5, 5],
         [5, 5, 5, 5]]], dtype=torch.uint8)
b的维度数(秩):3; 形状:torch.Size([2, 3, 4]); 所在设备:cpu; 元素个数:24; 元素类型:torch.uint8, 元素的字节大小:1
b bin:
 00000101
mand:
 tensor([[[1, 1, 1, 1],
         [1, 1, 1, 1],
         [1, 1, 1, 1]],

        [[1, 1, 1, 1],
         [1, 1, 1, 1],
         [1, 1, 1, 1]]], dtype=torch.int16)
ma

* 三角函数计算  

|函数|作用|
|:---|:---|
|cos|求输入元素的余弦|
|cosh|求输入元素的双曲余弦|
|sin|求输入元素的正弦|
|sinh|求输入元素的双曲正弦|
|tan|求输入元素的正切|
|tanh|求输入元素的双曲正弦|
|acos|计算输入中每个元素的反余弦|
|asin|计算输入元素的反正弦的新张量|
|atan|计算输入元素的反正切的新张量|
|atanh|返回一个新的张量，该张量具有输入元素的反双曲正切|

* 统计函数 

|函数|作用|
|:---|:---|
|mean|返回平均值|
|sum|返回总和|
|prod|计算所有元素的积|
|max|返回最大值|
|min|返回最小值|
|argmax|返回最大值排序的索引值|
|argmin|返回最小值排序的索引值|
|std|返回标准差|
|var|返回方差|
|median|返回中位数|
|mode|返回众数值|
|histc|计算输入的直方图|
|bincount|返回每个值的频数|

* 矩阵计算  

|函数|作用|
|:---|:---|
|mm/matmul/@|2-d矩阵乘法|
|mv|矩阵输入和向量vec的矩阵向量乘积|
|dot|1-d矩阵内积|

In [47]:
a = torch.randint(1, 10, size=(3, 4))
bvec = torch.randint(1, 10, size=(4,))
PrintTensor("a", a)
PrintTensor("bvec", bvec)
m_mv = torch.mv(a, bvec)
PrintTensor("m_mv", m_mv)

a:
 tensor([[9, 5, 1, 2],
        [3, 7, 5, 3],
        [1, 6, 2, 6]])
a的维度数(秩):2; 形状:torch.Size([3, 4]); 所在设备:cpu; 元素个数:12; 元素类型:torch.int64, 元素的字节大小:8
bvec:
 tensor([7, 8, 9, 3])
bvec的维度数(秩):1; 形状:torch.Size([4]); 所在设备:cpu; 元素个数:4; 元素类型:torch.int64, 元素的字节大小:8
m_mv:
 tensor([118, 131,  91])
m_mv的维度数(秩):1; 形状:torch.Size([3]); 所在设备:cpu; 元素个数:3; 元素类型:torch.int64, 元素的字节大小:8
